name: "Z-AUTOMATED: Data Pipeline Terraform Plan/Apply"

on:
  push:
    branches: [main]
    paths:
      - "stacks/step-function/**"
      - "stacks/transfer-classifier/**"
      - "stacks/validate_metrics/**"
      - "stacks/ods-downloader/**"
      - "stacks/reports-generator/**"
      - "stacks/spine-exporter/**"
      - "stacks/metrics-calculator/**"
      - ".github/workflows/automated-data-pipeline-terraform.yml"
      - ".github/workflows/deploy-stack.yml"
      - "../../lambdas/validate_metrics"

  pull_request:
    branches: [main]
    paths:
      - "stacks/step-function/**"
      - "stacks/transfer-classifier/**"
      - "stacks/validate_metrics/**"
      - "stacks/ods-downloader/**"
      - "stacks/reports-generator/**"
      - "stacks/spine-exporter/**"
      - "stacks/metrics-calculator/**"
      - ".github/workflows/automated-data-pipeline-terraform.yml"
      - ".github/workflows/deploy-stack.yml"

permissions:
  pull-requests: write
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout

jobs:
  step-function:
    uses: ./.github/workflows/deploy-stack.yml
    with:
      environment: dev
      is_deployment: ${{ github.ref == 'refs/heads/main' }}
      terraform_stack: step-function
      git_ref: ${{ github.ref }}
    secrets: inherit

  transfer-classifier:
    needs: step-function
    uses: ./.github/workflows/deploy-stack.yml
    with:
      environment: dev
      is_deployment: ${{ github.ref == 'refs/heads/main' }}
      terraform_stack: transfer-classifier
      image_tag: transfer_classifier
      git_ref: ${{ github.ref }}
    secrets: inherit

  validate-metrics:
    needs: transfer-classifier
    uses: ./.github/workflows/deploy-stack.yml
    with:
      environment: dev
      is_deployment: ${{ github.ref == 'refs/heads/main' }}
      terraform_stack: validate_metrics
      build_lambda: true
      git_ref: ${{ github.ref }}
    secrets: inherit

  ods-downloader:
    needs: validate-metrics
    uses: ./.github/workflows/deploy-stack.yml
    with:
      environment: dev
      is_deployment: ${{ github.ref == 'refs/heads/main' }}
      terraform_stack: ods-downloader
      image_tag: ods_downloader
      git_ref: ${{ github.ref }}
    secrets: inherit

  reports-generator:
    needs: ods-downloader
    uses: ./.github/workflows/deploy-stack.yml
    with:
      environment: dev
      is_deployment: ${{ github.ref == 'refs/heads/main' }}
      terraform_stack: reports-generator
      image_tag: reports_generator
      git_ref: ${{ github.ref }}
    secrets: inherit

  spine-exporter:
    needs: reports-generator
    uses: ./.github/workflows/deploy-stack.yml
    with:
      environment: dev
      is_deployment: ${{ github.ref == 'refs/heads/main' }}
      terraform_stack: spine-exporter
      image_tag: spine_exporter
      git_ref: ${{ github.ref }}
    secrets: inherit

  metrics-calculator:
    needs: spine-exporter
    uses: ./.github/workflows/deploy-stack.yml
    with:
      environment: dev
      is_deployment: ${{ github.ref == 'refs/heads/main' }}
      terraform_stack: metrics-calculator
      image_tag: metrics_calculator
      git_ref: ${{ github.ref }}
    secrets: inherit
